sonar.projectKey=RaviTeja110820_enterprise-product-deployment
sonar.organization=mysonarpro

sonar.host.url=https://sonarcloud.io

sonar.sources=src/main
sonar.tests=src/test

sonar.java.binaries=target/classes