pipeline {
    agent any

    environment {

        // AWS
        AWS_REGION      = 'ap-south-2'
        AWS_ACCOUNT_ID  = '705557196379'
        ECR_REPOSITORY  = 'enterprise-app'

        // EKS
        CLUSTER_NAME    = 'enterprise-product-eks'
        NAMESPACE       = 'enterprise'
        DEPLOYMENT_NAME = 'enterprise-app'
        CONTAINER_NAME  = 'enterprise-app'

        // Docker
        IMAGE_TAG = "v${BUILD_NUMBER}"
        IMAGE_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Application') {
            steps {
                dir('app') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Run Unit Tests') {
            steps {
                dir('app') {
                    sh 'mvn test'
                }
            }
        }

        stage('SonarCloud Analysis') {
            steps {
                dir('app') {
                    withSonarQubeEnv('SonarCloud') {
                        withCredentials([
                            string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')
                        ]) {
                            sh """
                            mvn sonar:sonar \
                            -Dsonar.projectKey=RaviTeja110820_enterprise-product-deployment \
                            -Dsonar.organization=mysonarpro \
                            -Dsonar.host.url=https://sonarcloud.io \
                            -Dsonar.token=${SONAR_TOKEN}
                            """
                        }
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('app') {
                    sh """
                    docker build \
                    -t ${ECR_REPOSITORY}:${IMAGE_TAG} .
                    """
                }
            }
        }

        stage('Trivy Security Scan') {
            steps {
                sh """
                trivy image \
                --severity HIGH,CRITICAL \
                --exit-code 1 \
                --no-progress \
                ${ECR_REPOSITORY}:${IMAGE_TAG}
                """
            }
        }

        stage('Login to Amazon ECR') {
            steps {
                sh """
                aws ecr get-login-password \
                --region ${AWS_REGION} | \
                docker login \
                --username AWS \
                --password-stdin ${IMAGE_URI}
                """
            }
        }

        stage('Push Docker Image') {
            steps {
                sh """
                docker tag ${ECR_REPOSITORY}:${IMAGE_TAG} ${IMAGE_URI}:${IMAGE_TAG}
                docker push ${IMAGE_URI}:${IMAGE_TAG}
                """
            }
        }

        stage('Update kubeconfig') {
            steps {
                sh """
                aws eks update-kubeconfig \
                --region ${AWS_REGION} \
                --name ${CLUSTER_NAME}
                """
            }
        }

        stage('Deploy to Amazon EKS') {
            steps {
                sh """
                kubectl set image deployment/${DEPLOYMENT_NAME} \
                ${CONTAINER_NAME}=${IMAGE_URI}:${IMAGE_TAG} \
                -n ${NAMESPACE}
                """
            }
        }

        stage('Verify Rollout') {
            steps {
                sh """
                kubectl rollout status deployment/${DEPLOYMENT_NAME} \
                -n ${NAMESPACE}
                """
            }
        }

        stage('Verify Deployment') {
            steps {
                sh """
                echo "Pods:"
                kubectl get pods -n ${NAMESPACE}

                echo ""

                echo "Services:"
                kubectl get svc -n ${NAMESPACE}

                echo ""

                echo "Deployment:"
                kubectl get deployment -n ${NAMESPACE}
                """
            }
        }
    }

    post {

        success {

            echo "========================================="
            echo "BUILD SUCCESSFUL"
            echo "========================================="
            echo "Image : ${IMAGE_URI}:${IMAGE_TAG}"
            echo "Application deployed successfully to Amazon EKS"
            echo "========================================="
        }

        failure {

            echo "========================================="
            echo "BUILD FAILED"
            echo "========================================="
        }

        always {

            sh """
            docker image rm -f ${ECR_REPOSITORY}:${IMAGE_TAG} || true
            docker image rm -f ${IMAGE_URI}:${IMAGE_TAG} || true
            docker image prune -f || true
            """

            cleanWs()
        }
    }
}